
//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Mon Feb 10 14:38:20 CST 2014
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  
  /**
   * 2 - 13:
   * bool  int   void  true  false  struct
   * cin   cout  if    else  while  return  
   */
  public static final int PLUSPLUS = 26;
  public static final int DIVIDE = 31;
  public static final int EQUALS = 35;
  public static final int GREATER = 38;
  public static final int LPAREN = 19;
  public static final int INT = 3;
  public static final int LESS = 37;
  public static final int MINUS = 29;
  public static final int WRITE = 24;
  public static final int RPAREN = 20;
  public static final int NOT = 32;
  public static final int SEMICOLON = 21;
  public static final int AND = 33;
  public static final int OR = 34;
  public static final int BOOL = 2;
  public static final int COMMA = 22;
  public static final int PLUS = 28;
  public static final int ASSIGN = 41;
  public static final int LESSEQ = 39;
  public static final int IF = 10;
  public static final int DOT = 23;
  public static final int ID = 14;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 27;
  public static final int RETURN = 13;
  public static final int TRUE = 5;
  public static final int LCURLY = 17;
  public static final int CIN = 8;
  public static final int VOID = 4;
  public static final int RCURLY = 18;
  public static final int INTLITERAL = 15;
  public static final int TIMES = 30;
  public static final int ELSE = 11;
  public static final int COUT = 9;
  public static final int READ = 25;
  public static final int NOTEQUALS = 36;
  public static final int WHILE = 12;
  public static final int GREATEREQ = 40;
  public static final int STRINGLITERAL = 16;
  public static final int FALSE = 6;
  public static final int STRUCT = 7;
}

